### ISSUE TITLE
cannot use tecoGAN-da-8x-std due to gpu-architecture

### ISSUE THREAD

**Issue by idl-polun** [km2ii/JVP_TG-PLUS#100]
Hi I am trying this new model with 4090, however it cannot run and prompt such error at last line
nvrtc: error: invalid value for --gpu-architecture (-arch)
the detail as attached file
[da_fail.txt](https://github.com/km2ii/JP109A_TG-PLUS/files/10317202/da_fail.txt)

I also try other model like basicVSR-pp and tecogan, and those are running well.
is this because pytorch doesn't support 4090 yet?

**Comment by tonyyuan1** [comment]
The same bug occurs with rtx4070ti too.

**Comment by idl-polun** [comment]
I upgraded 11.8 + cudnn-windows-x86_64-8.7.0.84 and replace these files in folder 
TG\TGMAIN\torch\lib\cublas64_11.dll
TG\TGMAIN\torch\lib\cublasLt64_11.dll
TG\TGMAIN\torch\lib\cudart64_110.dll
TG\TGMAIN\torch\lib\cudnn_adv_infer64_8.dll
TG\TGMAIN\torch\lib\cudnn_adv_train64_8.dll
TG\TGMAIN\torch\lib\cudnn_cnn_infer64_8.dll
TG\TGMAIN\torch\lib\cudnn_cnn_train64_8.dll
TG\TGMAIN\torch\lib\cudnn_ops_infer64_8.dll
TG\TGMAIN\torch\lib\cudnn_ops_train64_8.dll
TG\TGMAIN\torch\lib\cudnn64_8.dll
TG\TGMAIN\torch\lib\cufft64_10.dll
TG\TGMAIN\torch\lib\cufftw64_10.dll
TG\TGMAIN\torch\lib\curand64_10.dll
TG\TGMAIN\torch\lib\cusolver64_11.dll
TG\TGMAIN\torch\lib\cusolverMg64_11.dll
TG\TGMAIN\torch\lib\cusparse64_11.dll
TG\TGMAIN\torch\lib\nvrtc64_112_0.dll

I didn't chech which one did the magic, but it can run, guess it's nvrtc64_112_0 issue

**Comment by PhiGo67** [comment]
> I upgraded 11.8 + cudnn-windows-x86_64-8.7.0.84 and replace these files in folder TG\TGMAIN\torch\lib\cublas64_11.dll TG\TGMAIN\torch\lib\cublasLt64_11.dll TG\TGMAIN\torch\lib\cudart64_110.dll TG\TGMAIN\torch\lib\cudnn_adv_infer64_8.dll TG\TGMAIN\torch\lib\cudnn_adv_train64_8.dll TG\TGMAIN\torch\lib\cudnn_cnn_infer64_8.dll TG\TGMAIN\torch\lib\cudnn_cnn_train64_8.dll TG\TGMAIN\torch\lib\cudnn_ops_infer64_8.dll TG\TGMAIN\torch\lib\cudnn_ops_train64_8.dll TG\TGMAIN\torch\lib\cudnn64_8.dll TG\TGMAIN\torch\lib\cufft64_10.dll TG\TGMAIN\torch\lib\cufftw64_10.dll TG\TGMAIN\torch\lib\curand64_10.dll TG\TGMAIN\torch\lib\cusolver64_11.dll TG\TGMAIN\torch\lib\cusolverMg64_11.dll TG\TGMAIN\torch\lib\cusparse64_11.dll TG\TGMAIN\torch\lib\nvrtc64_112_0.dll
> 
> I didn't chech which one did the magic, but it can run, guess it's nvrtc64_112_0 issue

I tried the same, but still no luck with my RTX4070TI and Javplayer :(
