### ISSUE TITLE
Config.exe can't launch

### ISSUE THREAD

**Issue by tomeleon** [km2ii/JVP_TG-PLUS#106]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "ConfigTools.py", line 30, in init ConfigTools
ModuleNotFoundError: No module named 'hashlib'

**Comment by PQWAK** [comment]
same

**Comment by km2ii** [comment]
[ConfigTools.cp37-win_amd64.zip](https://github.com/km2ii/JVP_TG-PLUS/files/10578097/ConfigTools.cp37-win_amd64.zip)
My mistake, unzip and overwrite the ConfigTools.cp37-win_amd64.pyd in TG/TGMAIN

**Comment by PQWAK** [comment]
Thanks

**Comment by tomeleon** [comment]
Another problem.  I use 1.12b,but after extract images the app noticed "verify faild. Please use 1.12b"
But it's 1.12b already.
