### ISSUE TITLE
Error alert "verify faild....Please use 1.12b"

### ISSUE THREAD

**Issue by tomeleon** [km2ii/JVP_TG-PLUS#107]
I use javplayer 1.12b. But in recording process after extract images the app noticed "verify faild. Please use 1.12b"
But it's 1.12b already.

**Comment by km2ii** [comment]
If possible, send JavPlayer_Data\Managed\Assembly-CSharp.dll to [mail](mailto:ty4king@gmail.com).

**Comment by tomeleon** [comment]
Send mail already.

**Comment by tomeleon** [comment]
The  server alert the mail has been reject. Did U received any mail from tomeleon?

**Comment by km2ii** [comment]
Not received, it is recommended to apply the zip and password.

**Comment by tomeleon** [comment]
Re send

**Comment by tomeleon** [comment]
1.12b   password

**Comment by tomeleon** [comment]
向以下收件人或组传递邮件失败:

ty4king@gmail.com (ty4king@gmail.com)
你的邮件未送达，因为收件人的邮件提供程序拒绝了它。

**Comment by tomeleon** [comment]
Send failed again.
Because the gmail server reject any mail with .rar or .zip files.
Can U can give me some other address?

**Comment by km2ii** [comment]
upload by https://workupload.com/

**Comment by tomeleon** [comment]
OK.
The link send to your email.
1.12b  password

**Comment by km2ii** [comment]
The files are consistent. Post a screenshot of the reported error.

**Comment by tomeleon** [comment]
[https://workupload.com/file/azfZ9zaXjmt](url)

**Comment by tomeleon** [comment]
https://workupload.com/file/azfZ9zaXjmt

**Comment by km2ii** [comment]
Did the dos window for basicvsr-pp or tecogan-da pop up?
Are you using an older version of core_runner.cp37-win_amd64.pyd?
#103 The issue has been fixed and the method doesn't work.

**Comment by tomeleon** [comment]
https://workupload.com/file/kZuJtfCHARG

**Comment by km2ii** [comment]
https://workupload.com/file/5Qsx5WLktTr
overwrite the source file in tg/tgmain
if it still reports error, post screenshot.

**Comment by tomeleon** [comment]
Ok.It's done. I delete all the files of javplayer and TG-PLUS, redownload all of them. Then it's ok.
