### ISSUE TITLE
tgmain not found

### ISSUE THREAD

**Issue by PhiGo67** [km2ii/JVP_TG-PLUS#108]
Maybe AMD cpu related.
When I choose TecaGAN-DA in the configtool, I get the error when super resolution processing begins:
MyPath\TG\tgmain.exe 0 TG-STD input0 output0
Command "tgmain.exe" spelled wrong or can´t be found.

MyPath\TG\BATCH>pause
Press any key...

It only happens with TecoGAN-DA, other models work fine.

**Comment by km2ii** [comment]
![image](https://user-images.githubusercontent.com/55206195/216763281-37c4f7df-b089-436b-8352-7c7c6db0ce35.png)
4000 series graphics cards cannot call tecogan-da, please refer to #100.

**Comment by suphamster** [comment]
I also have sometimes (randomly) this error on NV 1060 GTX 6Gb.

**Comment by suphamster** [comment]
Also TecaGAN-DA has sometimes problem with input/output images amount not the same message and if it skipped video wouldn't be decensered at all. If I switch to any other decensoring model all uncensors fine.

**Comment by km2ii** [comment]
most of errors are due to insufficient vrm.
try to reduce the n-count value.


suphamster ***@***.***> 于2023年2月14日周二 22:08写道：

**Comment by km2ii** [comment]
most of mismatch errors are due to insufficient vrm.
Try to reduce the n-count value.

**Comment by suphamster** [comment]
> most of mismatch errors are due to insufficient vrm. Try to reduce the n-count value.

Thanks. but I think in this case u could be wrong because mismatch problem happens on **720p** videos only with TG-DA model, but when I upscale video to 1080p all works fine. So I'm pretty sure that 1080p video should use more VRAM than 720p.

**Comment by suphamster** [comment]
> most of mismatch errors are due to insufficient vrm. Try to reduce the n-count value.
I've already have it set to 1 so sadly there are nothing to reduce here...

**Comment by suphamster** [comment]
> most of mismatch errors are due to insufficient vrm. Try to reduce the n-count value.

Thanks, reducing it twice seems fixed mismatch problem.
