### ISSUE TITLE
Additional super resolution fails with VEAI 

### ISSUE THREAD

**Issue by SyntaxError1871** [km2ii/JVP_TG-PLUS#109]
Additional super resolution fails with VEAI:

![image](https://user-images.githubusercontent.com/48274164/217330340-75c7ca12-c528-4b8a-bae0-f0078295b853.png)

![image](https://user-images.githubusercontent.com/48274164/217330379-faf99dc4-7364-4579-b64b-419ea6d15526.png)

What's weird is that sometimes it does work but then it doesn't, and I can't figure out how to get it working again, so there's something "unreliable" about the process going on.

I am using VEAI 2.3.0.

**Comment by km2ii** [comment]
> Mixing with sra mode is not supported.
![image](https://user-images.githubusercontent.com/55206195/217505422-bb9bdcb1-6b6c-40eb-ac38-8c6dc68ab96e.png)

> Make sure the record option selects tgmain and none, use configtools to configure the veai process.
![image](https://user-images.githubusercontent.com/55206195/217506749-101b78d8-b8c4-43ce-9047-274ef1edd45f.png)
![image](https://user-images.githubusercontent.com/55206195/217506089-b36d79b6-65fb-410a-b1ee-5e0981098466.png)

**Comment by SyntaxError1871** [comment]
OK thank you - should I be seeing VEAI 2.3.0 window pop up to process when VEAI is one of the steps in TG-PLUS? I do not notice it opening like it does if SRA-VEAI or SRA-VEAI2 was enabled in Javplayer before.

**Comment by km2ii** [comment]
The veai window should pop up normally, if it does not it means that it is not called properly.
Need to check the veai installation path and specify it in the veai tab.

**Comment by SyntaxError1871** [comment]
When I try to specify path for veai, it doesn't seem to save. I can't click "Select file" to pick executable, and if I try manually specifying path, it does not retain this setting, even if I modify the config.ini file. 

![image](https://user-images.githubusercontent.com/48274164/217987388-0cc9ecfa-ceb0-4157-abed-0a8cbe75f83a.png)
![image](https://user-images.githubusercontent.com/48274164/217987442-4a385014-4902-4a9c-b600-4d4f3b74fc10.png)

**Comment by km2ii** [comment]
![image](https://user-images.githubusercontent.com/55206195/218070519-4f9b1b41-6773-489c-9bb1-b015fe42ebf9.png)

**Comment by SyntaxError1871** [comment]
Thank you, that patch worked.
