### ISSUE TITLE
Adjust VRAM usage per TG-PLUS thread

### ISSUE THREAD

**Issue by SyntaxError1871** [km2ii/JVP_TG-PLUS#110]
Hello,

Is there any way to adjust the amount of VRAM utilized per TG-PLUS thread? 

The Javplayer settings seems to control the amount of threads that can run but I do not see any setting anywhere in config file or application to adjust maximum VRAM per thread. I have RTX 3090 with 24GB of VRAM so I want to maximize amounts of threads without completely maxing out memory (to like 22GB usage if possible) to be more efficient. I can currently do 2 threads maximum because if I go over 2 threads I go over 24GB of VRAM usage and things can error out, but I think this can be more efficient since core utilization is relatively low while VRAM usage is high so if I can adjust threads to 4 and cap VRAM usage per thread to like 5GB each that would be ideal.

![image](https://user-images.githubusercontent.com/48274164/218153384-c920305f-80bd-40f9-afbc-4507b48d3de5.png)

**Comment by km2ii** [comment]
Limiting the vrm does not reduce vam requirements.

**Comment by idl-polun** [comment]
Just like your case, 4090 sometimes run out of memory especially with tecogan-da model.
tecogan-da uses 2 threads, bvpp 3 or 4 threads in my environment otherwise kernel panic may occur.

**Comment by qczhao** [comment]
I found this problem at 4090 with cuda12. One bvpp threads may use 6GB-9GB VRAM. 
and I found set fp16 off , One bvpp threads only use 2GB-4GB VRAM.

**Comment by qczhao** [comment]
i found set fp16=false maybe reduce vram usage
