### ISSUE TITLE
Hello km2ii , may you upload the tg-plus?

### ISSUE THREAD

**Issue by FrankLinxzx** [km2ii/JVP_TG-PLUS#111]
Dear km2ii 
may you upload the tg-plus?
thx
https://imgur.com/ZTeBhHX.jpg

**Comment by km2ii** [comment]
Version v.02 is out of date and no new version is available at this time.

**Comment by calro-lam** [comment]
dear km2ii the lastest tg-plus  v0.3.02.02 can't use amd's gpu to procress. when i open the super test , the  Utilization of cpu has been reach 100%. as the same time , the Utilization of gpu is reaching 5%～7%.

**Comment by km2ii** [comment]
> dear km2ii the lastest tg-plus v0.3.02.02 can't use amd's gpu to procress. when i open the super test , the Utilization of cpu has been reach 100%. as the same time , the Utilization of gpu is reaching 5%～7%.

AMD gpu not supported.
