### ISSUE TITLE
TopazVideoEnhanceAI2.3.0 mistake

### ISSUE THREAD

**Issue by mzxcvbnm** [km2ii/JVP_TG-PLUS#116]
Start TopazVideoEnhanceAI without JavPlayer it is not available. mistake..
![Screenshot_20230316_223150](https://user-images.githubusercontent.com/30436682/225788025-ddd8ea13-c444-4bf6-8752-73c045268fe1.jpg)
![IMG_20230316_215338](https://user-images.githubusercontent.com/30436682/225788053-b38d80bd-0286-476c-849b-2788e56c31b3.jpg)

**Comment by km2ii** [comment]
Do you know what you're performing? Scaling 1920x1080 to 11520x6480?
