### ISSUE TITLE
Hi can i ask something?

### ISSUE THREAD

**Issue by hello-hi5** [km2ii/JVP_TG-PLUS#121]
Hi 
Understand the inability to be a translator

Working on only the mosaic part during work. Is it possible to skip the non-mosaic part?

and my cpu is working 99%. gpu is just average 40% is it normal? or is there a problem?

my cuda version cuda 11.3.1 cudn-11.3 v8.2.1.32.
is it okay upgrade newest cuda version? 

thank you for your program

**Comment by km2ii** [comment]
The mosaic part by the main program, nothing can do.
GPU occupancy is completely normal, don't worry about it.
Upgrading cuda is ok, it's just my environment.

**Comment by hello-hi5** [comment]
thank you!
