### ISSUE TITLE
cannot execute da from UnboundLocalError

### ISSUE THREAD

**Issue by idl-polun** [km2ii/JVP_TG-PLUS#125]
I am trying the latest version, however I got such error with some sections.

[info] D:\JavPlayer_112b_TGP_0320\TG\TG-MODEL\tecoGAN-da-8x-std-ep1.pth loaded.
 input shape: [112, 100]
 output shape: [896, 800]
Traceback (most recent call last):
  File "tecogan-da.py", line 5, in <module>
  File "core_tecogan_da.py", line 1036, in core_tecogan_da.main
  File "core_tecogan_da.py", line 1039, in core_tecogan_da.main
UnboundLocalError: local variable 'wm_pos' referenced before assignment
[1092] Failed to execute script 'tecogan-da' due to unhandled exception!

I've wiped config.ini and more weired thing is that I can execute manully without this error.

**Comment by idl-polun** [comment]
fail command: tgmain 0 TG-STD 64 1

pass one: tecogan-da.exe --input_dir D:\JavPlayer_112b_TGP_0320\TG\input64 --output_dir D:\JavPlayer_112b_TGP_0320\TG\output64 --checkpoint D:\JavPlayer_112b_TGP_0320\TG\TG-MODEL\tecoGAN-da-8x-std-ep1 --imgext png --n_count 60 --warm_inter 5 --offset_x 0 --offset_y 0

however fail command that calls the same command at last.
It may something wrong when tgmain creates subprocess

**Comment by km2ii** [comment]
I will check this and thank you for your feedback.

**Comment by km2ii** [comment]
https://workupload.com/file/58BZPZTa5XM

**Comment by idl-polun** [comment]
cool, it works now

**Comment by idl-polun** [comment]
oops, it got similar issue when running bvpp, it can run manually but not from tgmain

basicVSR-pp.exe --input_dir D:\JavPlayer_112b_TGP_0320\TG\input217 --output_dir D:\JavPlayer_112b_TGP_0320\TG\output217 --checkpoint D:\TG\TG-MODEL\basicVSR-pp-8x-std-ep2 --scale 8 --imgext png --n_count 30 --warm_inter 5 --offset_x 0 --offset_y 0
[info] C:\Users\lblcs\Downloads\JavPlayer_112b_TGP_0320\TG\TG-MODEL\basicVSR-pp-8x-std-ep2.pth loaded.
 input shape: [74, 150]
 output shape: [592, 1200]
Traceback (most recent call last):
  File "basicVSR-pp.py", line 5, in <module>
  File "core_basicVSR_pp.py", line 1168, in core_basicVSR_pp.main
  File "core_basicVSR_pp.py", line 1171, in core_basicVSR_pp.main
  File "random.py", line 261, in choice
IndexError: Cannot choose from an empty sequence

**Comment by km2ii** [comment]
new_patcher: https://workupload.com/file/3GM5VBBLYRx
