### ISSUE TITLE
Please confirm whether TG-Plus calls TVAI.

### ISSUE THREAD

**Issue by Great168** [km2ii/JVP_TG-PLUS#128]
I want to use Javplayer with TG-Plus and TVAI 3.1.8, I've followed the author's instructions on the release page to set it up, but I don't see any trace of calling TVAI either in the consoles or in the task manager. How to judge whether TG-Plus calls TVAI? Please confirm whether TG-Plus calls TVAI. Thanks!

**Comment by km2ii** [comment]
1. Not sure what you mean.
2. First, make sure that TVAI operates normally in the GUI mode.
3. Check whether the environment variables are set correctly.
4. Open a command line window to execute:
```
cd tg/tgmain,
tgmain.exe 0 TG-STD 0 1
```
5. Check the output information.


This is a simple configuration and TVAI output information.
config:
![image](https://user-images.githubusercontent.com/55206195/228274892-71380657-7a47-4631-b10d-42f8b185b4d8.png)
outputs:
![image](https://user-images.githubusercontent.com/55206195/228276513-aa2600e2-adec-415c-b5cf-a7aec24a1bcb.png)

**Comment by Great168** [comment]
I get the following:
![image](https://user-images.githubusercontent.com/128937784/228375223-3eef4ed1-d944-4c3a-9c08-2ececc913fc6.png)

**Comment by Great168** [comment]
I will test it. Thank you very much

**Comment by tw042449** [comment]
![未命名](https://user-images.githubusercontent.com/129298830/228559286-586a6567-e270-450b-98f1-2be1375b6175.png)

what can i do PLS!

**Comment by tw042449** [comment]
![未命名](https://user-images.githubusercontent.com/129298830/228574775-d5810628-6b41-43db-923f-bbabfa3948a9.png)
Reinstallation is the same. Is it a CUDA version problem? I am using 12.1

**Comment by km2ii** [comment]
> Reinstallation is the same. Is it a CUDA version problem? I am using 12.1

The hint message is very obvious. Try to delete output directory is denied.
Check if there is other software that is occupying the output directory.
Close such as image viewer, antivirus software, etc.

**Comment by tw042449** [comment]
I have turned everything off and still the same

**Comment by tw042449** [comment]
I tried to set tgmain.exe and runGan.exe as ADMIN to start
As a result, output0 came out but also made an error
![未命名2](https://user-images.githubusercontent.com/129298830/228615754-9455c1b4-8594-4190-87ce-2951faa4a19c.png)

**Comment by Great168** [comment]
![image](https://user-images.githubusercontent.com/128937784/228711868-8dcf7378-851a-4a47-a987-363e1ea98f97.png)
What I got is the picture above, which seems to be different from the author's picture, is this correct?

**Comment by km2ii** [comment]
The output info may be different for each version, but should be the same with same version.
1. Please confirm tvai is 3.1.8?
2. Under the gui interface, select the image sequence and execute the same model, is the output normal?
3. Check the image size in the output, if output size is right, then tvai is called normally.

The corresponding model will be downloaded automatically under the command line interface, but there is no prompt message, which may cause the model download failure due to firewall, not properly logged in and other factors.

**Comment by tw042449** [comment]
Your m1 and m2 are different from the author
