### ISSUE TITLE
utf-8 codec can't decode byte error

### ISSUE THREAD

**Issue by love2y** [km2ii/JVP_TG-PLUS#129]
Hello.

Occur this error. when Javplayer 1.11b version super-resoulation process.

"No images have been  processed at all"

Original TG is no problem.
Check please.

**Comment by love2y** [comment]
I already solved. 
I had changed an option in Windows.

**Comment by grv888** [comment]
Same 
![image](https://user-images.githubusercontent.com/63555514/229026916-42add20d-2f5e-408a-b902-7a3df8b207ea.png)

**Comment by grv888** [comment]
just download latest topaz and everything works 2.3 not worked
