### ISSUE TITLE
Cannot use tecogan-da with TG-Plus v0.3.03.20

### ISSUE THREAD

**Issue by teijiIshida** [km2ii/JVP_TG-PLUS#130]
Hello,

Whenever I try to use tecogan-da with TG-Plus v0.3.03.20 (Javplayer v1.12b), I get the following error ( https://imgur.com/a/WP9xAMu )

I tried it on a fresh installation of Javplayer v1.12b. But if I use the older TG-Plus v0.3.02.02, it works good and no error.  Bug in new version maybe?

**Comment by teijiIshida** [comment]
Additional info:

These are 2 fresh install of JavPlayer v1.12b + TG Plus (no other mods).

TG PLUS V0.3.02.02_JavPlayer_112b: https://imgur.com/a/j0IfVm6
It produces an error when running the command "tgmain.exe 0 TG-STD inputX outputX". However, when Recording in JavPlayer, it works fine and no error.

TG PLUS V0.3.03.20_JavPlayer_112b: https://imgur.com/a/g5ezfra
It produces an error when running the command "tgmain.exe 0 TG-STD inputX outputX". And also produces the error shown in the image when Recording in JavPlayer.

**Comment by km2ii** [comment]
X is the serial number of the image sequence.
Example: tgmain.exe 0 TG-STD input0 output0

**Comment by km2ii** [comment]
Your display screen is a bit messy, suggest changing it to:

**Comment by km2ii** [comment]
Your display screen is a bit messy, suggest changing it to:
![image](https://user-images.githubusercontent.com/55206195/229260095-0fc81ad5-ad3b-44bb-8dc7-34163eda898d.png)

**Comment by teijiIshida** [comment]
Ok, here are the screenshots of the commands:

V0.3.02.02: https://imgur.com/a/Kydl9Rb

V0.3.03.20: https://imgur.com/a/mE4fSNN

**Comment by teijiIshida** [comment]
> Your display screen is a bit messy, suggest changing it to: ![image](https://user-images.githubusercontent.com/55206195/229260095-0fc81ad5-ad3b-44bb-8dc7-34163eda898d.png)
I am using Console.

**Comment by km2ii** [comment]
**Error:**
![image](https://user-images.githubusercontent.com/55206195/229260789-8ec3f97b-a1a1-4d40-af75-cd8348f87a2d.png)
**Check whether the file exists:TG\TGMAIN\av.libs\.load-order-av-10.0.0**
![image](https://user-images.githubusercontent.com/55206195/229260907-b67b7e43-6a7d-416a-a9a7-abf062dcb10b.png)
If it does not exist, re-download the package again.

**Comment by km2ii** [comment]
win11? 
Try other options, such as: single console
> I am using Console.

**Comment by teijiIshida** [comment]
> 


I do have that file, but it doesn't have a . in front though. https://imgur.com/a/SicxvWE

I am using Windows 11 x64 2H22. I'm not sure I understand single console. Windows 11 console can use tabs, but I'm not opening multiple tabs (so, it's already single console?).

**Comment by teijiIshida** [comment]
I got it. It was indeed that file. I renamed it to ".load-order-av-10.0.0" and it works with no error now! https://imgur.com/a/OJQ05nh

**Comment by km2ii** [comment]
try:copy load-order-av-10.0.0 .load-order-av-10.0.0
![image](https://user-images.githubusercontent.com/55206195/229261914-3bbfdae3-4206-4ddc-a424-05963d30af07.png)
