### ISSUE TITLE
Cannot use veai's ahq

### ISSUE THREAD

**Issue by teijiIshida** [km2ii/JVP_TG-PLUS#133]
For some reason, I cannot use veai's ahq (I can use veai's prob though). I keep getting "invalid metadata version" (see pic).

I'm using JavPlayer 1.12b and TGPlus v03.03.20. My VEAI is v2.3.0. I reinsstalled Javplayer and VEAI multiple times, but it's still the same. Any help?

https://imgur.com/a/j1Ri5pa

**Comment by km2ii** [comment]
1.Invalid metadata does not affect veai operation, you can delete the folder JavPlayer_112b\TG\TGMAIN\PySide6\plugins\platforms to remove this warning message.
![image](https://user-images.githubusercontent.com/55206195/229996634-0024ff17-addc-4bb8-99bf-f4aa3a0f722d.png)
![image](https://user-images.githubusercontent.com/55206195/229996306-85f3e4fc-0313-47c9-915f-99a283021e61.png)
2.The veai warning message in configtools means that it failed the detection and could not call veai.
![image](https://user-images.githubusercontent.com/55206195/229997005-b4e0fd12-401c-4f60-b12a-0a9561a2a498.png)
First run Topaz Video Enhance AI.exe manually to make sure veai is running properly.
![image](https://user-images.githubusercontent.com/55206195/229996522-5ed8b470-ee54-4d74-afc0-586cfe220c9f.png)

**Comment by teijiIshida** [comment]
I could run Topaz Video Enhance AI.exe manually: https://imgur.com/a/OQkW57E

But if I use veai ahq, it pop up the Topaz app and loading model for a sec, then disappear. If I use veai ahq, the Topaz app pop up and load model and shows side by side processing as normal. The weird thing is I used to be able to do ahq last week. I don't know what happen to make it stop working. And even after reinstalling JavPlayer, TG Plus, Topaz 2.3.0, ahq still refuses to work.
