### ISSUE TITLE
How can I get clear and sharp video by TVAI?

### ISSUE THREAD

**Issue by Great168** [km2ii/JVP_TG-PLUS#134]
So far, I always feel that TVAI is not as clear and sharp as VEAI. There is no TVAI-related process in the task manager, and there is no newly downloaded model in the TVAI model directory. But as I change TVAI model, I indeed see different effects. Is this correct? Or how should I do to get the same clear and sharp setting as VEAI, ahq 4x?

**Comment by km2ii** [comment]
1.The tvai's are called via ffmpeg and the process is ffmpeg.
2.The download directory for tvai models is: C:\ProgramData\Topaz Labs LLC\Topaz Video AI\models
3.No one is saying tvai is better than veai, but it is not worse.
The easiest way to test is by the command:
`tgmain.exe 0 TG-STD input0 output0`
Configure one without tvai and another with tvai 4x, and compare the output image differences.
Or one use tvai and another use veai.

**Comment by Great168** [comment]
Thanks for your kind response!

With TVAI it is clearer than without, but I still think veai ahq x4 is clearer than TVAI ahq-11 x4.
Please tell me which TVAI model is corresponding to veai ahq x4?

**Comment by Great168** [comment]
I think the clarity and sharpness of TVAI is not as good as VEAI, I suggest that the author can improve it in the next version, thank you very much

**Comment by km2ii** [comment]
Thanks for your support, will do the test sometime.
But it depends on topaz.
I think topaz is pruning the model to run faster at the expense of quality.
