### ISSUE TITLE
What's the best combination of settings?

### ISSUE THREAD

**Issue by Hiy3333** [km2ii/JVP_TG-PLUS#136]
Hi

I've tried a few combinations, but they're not as good as other people's work.

Can you recommend me? What's the best combination of settings? please

**Comment by km2ii** [comment]
There is no universal combination of models.
The type of mosaic is very important.
For some thin types before 2016, good results can be achieved using only ep1/ep2/da models.

**Comment by km2ii** [comment]
I have organized the documentation and hope it will help you, but there is no fixed combination.
reference: https://github.com/km2ii/JVP_TG-PLUS/wiki/How-to-works-better
