### ISSUE TITLE
When the program reaches the encoder, it stops and does not act

### ISSUE THREAD

**Issue by tw042449** [km2ii/JVP_TG-PLUS#137]
![未命名](https://user-images.githubusercontent.com/129298830/230750245-a1451307-abe6-40fc-a837-1916c19b07d3.jpg)

M1-BVPP EP2 M2-denoise tla LOW After two runs, it is normal to enter the encoder, but it is stuck here and does not move, but the 5-second video is normal. I have divided the 20-minute video for recording, how can i fix it pls

**Comment by km2ii** [comment]
The encoding mode is done by the main javplayer program, it is not a function of this mod, it is recommended to restore the default settings of javplayer.
Here are settings for reference.
![image](https://user-images.githubusercontent.com/55206195/230755114-c04c0a2f-0833-40ac-ad36-9c1ead644b8a.png)
![image](https://user-images.githubusercontent.com/55206195/230755083-c2cd08de-73cd-40e3-907e-d98ec32a7c30.png)
