### ISSUE TITLE
could not use tvai

### ISSUE THREAD

**Issue by goatsyf** [km2ii/JVP_TG-PLUS#138]
when i use tvai model,it's always show this error
![Desktop 2023 04 04 - 20 27 09 02 mp4_20230404_202848 095](https://user-images.githubusercontent.com/120884567/230871399-0b7d32f6-3f23-41c7-bbf7-8a33c44bc950.jpg)

how can i solve this problem

**Comment by km2ii** [comment]
### [v0.3.03.20_patcher(20230410)](https://workupload.com/file/f3sD2JEHZRD) (532.19 KB)
 Fixed tvai bug, support jpg image format now.
*Overwrite the source files in TG/TGMAIN.*

**Comment by goatsyf** [comment]
alright thanks a lot
