### ISSUE TITLE
Cannot choose from empty sequence

### ISSUE THREAD

**Issue by cetaph230** [km2ii/JVP_TG-PLUS#143]
![image](https://user-images.githubusercontent.com/130883321/232265205-a52c2deb-77a1-4b0a-bdb8-485d51394924.png)

**Comment by km2ii** [comment]
Install the patch. [v0.3.03.20_patcher(20230410)](https://workupload.com/file/f3sD2JEHZRD) (532.19 KB)
https://github.com/km2ii/JVP_TG-PLUS/issues/125#issuecomment-1483729476
