### ISSUE TITLE
failure warning

### ISSUE THREAD

**Issue by mzxcvbnmqg** [km2ii/JVP_TG-PLUS#146]
use 8X model stage.
![IMG_20230423_201639](https://user-images.githubusercontent.com/101460375/233870977-c78c5df6-7692-434f-9cbc-05475e33ba62.jpg)
![Uploading IMG_20230423_201639.jpg…]()

 There is a fault, how to solve it?

**Comment by km2ii** [comment]
Too little information provided to help you, if the error recurs please provide:
1. The reported error config.ini.
2. Refer to #131 to provide a screenshot of the test command line.
3. Input image size.
