### ISSUE TITLE
Would you consider removing the TG-Plus watermark?

### ISSUE THREAD

**Issue by teijiIshida** [km2ii/JVP_TG-PLUS#152]
Most streaming website uses the standard TG with some general settings because they want to get their videos out as fast as possible for the clicks/views. But people who use TG-Plus are usually enthusiasts who want to take their time and patience to perfect the videos of their favorite AV actresses for personal viewing and not for commercial reasons. Also, JavPlayer already has a watermark that pops in and out constantly. Having an additional watermark from TG-Plus is unnecessary and kinda ruins the viewing experience for enthusiasts. Would you consider removing the TG-Plus watermark? Please?

**Comment by chatchatlotus** [comment]
I'd agree with teijilshida that extra watermark is not a must have. or make the watermark at the corner  instead of randomly popping up at the "important spot"

Anyway it's a very job you have done so far. GOOD JOB.

**Comment by chatchatlotus** [comment]
btw i am using the previous version of tg-plus and bvpp-ep1. using offset x -3  y-4 as mentioned in scanlover, are these offsets correct?

**Comment by km2ii** [comment]
>  Would you consider removing the TG-Plus watermark? 
1. After the release of v.03.02.02, a large number of videos made by the ep1 model began to spread.
2. Add watermark in v.03.03.20, the purpose is to limit the video transmission by ep2 model, it seems to have played a role.
     Watermarks are added to limit spreading, especially for commercial purposes.
     Under 30 seconds clips are used for test, without watermark.
     v.03.02.02 is still open for use, if you disgusted with watermark, you can continue to use this version.
3. The next version will consider other solutions such as reducing the frequency of watermarking or limiting the duration.
4. The official Twitter said that the next version of jvp may restrict the use of javplayer to play. My understanding is that it is very likely that the video decoded by this machine can only be played by this machine. The purpose is to limit the spread and reduce possible risks.

**Comment by teijiIshida** [comment]
> The next version will consider other solutions such as reducing the frequency of watermarking or limiting the duration.
Ok. If you still decide to add the watermark, can you put the watermark around the edges instead of right in the middle of the video? Sometimes, the watermark is blocking the view of the thing it's de-censoring (the genitals).

Thank you so much for your awesome work on the mod.

**Comment by idl-polun** [comment]
agree with @teijiIshida , it already adds one watermark in original version, the mod adds another.
it pays so much effort to de-censoring but put watermark on it, please conisder to remove or set on the corner.

**Comment by Chenqqingyang** [comment]
It turns out that the pirated images downloaded by BitTorrent have watermarks, but later they didn't. Why is it that no one downloads it because it really affects the perception!

**Comment by km2ii** [comment]
Discuss the issue further until a decision is made.
