### ISSUE TITLE
tgmain

### ISSUE THREAD

**Issue by blackziploc** [km2ii/JVP_TG-PLUS#153]
Tgmain calling vspipe appears to cause a memory leak when performing conversion on a large video (2h46m @22.1GB)

Currently the application is using 31.9GB of system RAM.

TG-PLUS is working correctly as smaller and shorter videos are processing correctly and disk usage is showing as normal.

**Comment by blackziploc** [comment]
Update: I manually updated vspipe from their website and this is have corrected this issue. I'll continue with the rendering and close if resolved

**Comment by hzg4027** [comment]
> 更新：我从他们的网站手动更新了 vspipe，这已经纠正了这个问题。我继续渲染并在解决后关闭

May I know which version has been updated?

Is it necessary to directly overwrite the latest version to the corresponding directory?

**Comment by blackziploc** [comment]
> May I know which version has been updated?

I used [R62](https://github.com/vapoursynth/vapoursynth/releases/tag/R62). According to their page R61 fixed the memory leak and R62 fixed audio issues.

> Is it necessary to directly overwrite the latest version to the corresponding directory?

Yes. After installing TG-PLUS the update required directly overwriting the applicable files (Not all files in the vspipe folder are directly from the vspipe repository.

**Comment by hzg4027** [comment]
> > May I know which version has been updated?
> 
> I used [R62](https://github.com/vapoursynth/vapoursynth/releases/tag/R62). According to their page R61 fixed the memory leak and R62 fixed audio issues.
> 
> > Is it necessary to directly overwrite the latest version to the corresponding directory?
> 
> Yes. After installing TG-PLUS the update required directly overwriting the applicable files (Not all files in the vspipe folder are directly from the vspipe repository.
> 
> Edit / Update: Since updating vspipe to R62 I have had no issues. Currently rendering and on 129/455. It has been 11 hours since I began but I am using a slower hard drive as the folder size exceeds 300GB currently

I downloaded VaporSynth64 Portable-R62 and overwritten all files under the (TG\TGMAIN\Vaporsynth) directory, but it did not run properly

**Comment by blackziploc** [comment]
I re-applied the patcher archive in order for TG-PLUS to run again. I also only overwrote the applicable files (installing javplayer, then installing tg-plus, extracting the portable vspipe archive to the tgmain\vaporsynth, then extracting the pacther archive again)

The vspipe.exe file size before updating was 60.0kb. After updating it is 103kb. I backed up the old files and new if you would like me to provide any files / proof

**Comment by blackziploc** [comment]
> Replace only the vspipe.exe file?

No, I extracted the entire VapourSynth64-Portable-R62.7z to the folder. Windows asked to overwrite the files and I allowed.

Then I used [your patcher](https://workupload.com/file/f3sD2JEHZRD) again and it worked

**Comment by blackziploc** [comment]
No problem. As I personally have resolved this I'll let you close this issue unless there's any other troubleshooting you with to try

**Comment by km2ii** [comment]
**There is nothing wrong with vspipe, no need to replace.**
The consumption of memory is huge. 
When the denoise threads exceeds 3, 32G is possible.

**Comment by km2ii** [comment]
The vspipe between different versions is not universal and cannot be replaced at will.
![image](https://user-images.githubusercontent.com/55206195/236294362-12c74b65-8928-458c-8768-0cf7bd16e46d.png)

**Comment by blackziploc** [comment]
ahh okay. since your screenshot is relevant to the original issue I had I will close the ticket. Thank you!
