### ISSUE TITLE
[tecogan-da] The number of files in input83 and output83 does not match

### ISSUE THREAD

**Issue by unicaja** [km2ii/JVP_TG-PLUS#155]
I'm using v0.3.02.02 version and encounter this error.
I know most of the issue is caused by lack of VRAM, but this one looks not.
Hope you can help me, thanks a lot!

Here's my mplus setting
![1](https://user-images.githubusercontent.com/132571190/236284481-17e8f535-8351-428e-8e5c-e660e0995d82.png)

The error at input83 and output83
![2](https://user-images.githubusercontent.com/132571190/236284918-280a121d-8967-4de8-a56b-941cdba802f8.png)

After I rightclick to ignore it, a new error comes.
Input47 and output47 does not match. And the error looks different
![3](https://user-images.githubusercontent.com/132571190/236285815-16ffdec4-2a21-47f3-899f-abf57dec74b2.png)

I ignore it again and finish the encoding, then go on to work with another film.
The same error come out at output111, output103 :
![5](https://user-images.githubusercontent.com/132571190/236291857-7da48978-0921-4a41-9e60-6f0b5fe0354c.png)

I wonder if you can help me? If it's not so complicated.

**Comment by idl-polun** [comment]
you should upgrade tgp to the latest version, it has been fixed at [TG-Plus for JVP_1.12b v0.3.03.20], check Item.5

**Comment by km2ii** [comment]
Turned off the watermark, you can now use v0.3.03.20 with new patcher.

**Comment by unicaja** [comment]
> Turned off the watermark, you can now use v0.3.03.20 with new patcher.
Nice, now I don't have to stick with the old version.
Thank you so much!

**Comment by unicaja** [comment]
I should leave the thread opened for a while.
If you guys using TG-PLUS and want this mod keep getting better.
You can buy a coffee on ko-fi to support the author. 
It's only 5 dollar, not much, but show that someone is appreciating his work.

**Comment by georgechoo1990** [comment]
Hi there, i have the same problem, i was using only 1 method "BasicVSR-pp-8x-std-ep2" and it show this out input does not match output error on certain video, i am using the latest version of  TG-Plus for JVP_1.12b v0.3.03.20 and apply the v.03.03.20a_patcher(20230506)  as well
