### ISSUE TITLE
v.03.03.20a_patcher(20230506) config_error

### ISSUE THREAD

**Issue by Hellgate4** [km2ii/JVP_TG-PLUS#157]
![capture](https://user-images.githubusercontent.com/100894620/236548876-14552409-0153-4675-9eac-976e8736c4af.png)
1.Error when running config for new patch. Please check.  05/06 am 03:00

2.If you roll back to the previous version, it will work normally.  05/06 am 04:30

3.The file dated 3/20 of ConfigTools.cp37-win_amd64 has no problem running, but if you change it to a patch dated 5/6, it 
   prints the same error as above.  05/06 am 11:20

**Comment by pyoseong** [comment]
I'm having the same problem.

**Comment by teijiIshida** [comment]
I don't have that problem. I'm using the ConfigTools (5.41MB) from the "TG-Plus for JVP_1.12b v0.3.03.20 (2.63 GB)."

**Comment by Hellgate4** [comment]
> I'm using it like that, but it's not without problems.
20230506 Patch file may have a problem, so please check it.



> 나는 그 문제가 없습니다. "TG-Plus for JVP_1.12b v0.3.03.20(2.63GB)"의 ConfigTools(5.41MB)를 사용하고 있습니다.

**Comment by PQWAK** [comment]
me too,the same problem

**Comment by Hellgate4** [comment]
As TeijiIshida wrote, the problem seems to be the file config file before the partial patch among the 3/20 update files.

Check the main configTools.exe 5,551kb file on 3/20 and the configTools 1,156kb file in TGMAIN
Please replace it

In my case, there was an error because the previous file was the main configTools.exe 3,998kb file and the configTools.exe 1,088kb file in TGMAIN.

Please refer to the content

**Comment by km2ii** [comment]
If this happens, please re-download the v.03.03.20 package and apply the new patch again, because the initial package has been updated once.
