### ISSUE TITLE
How can I solve the halo problem? 

### ISSUE THREAD

**Issue by happy2026** [km2ii/JVP_TG-PLUS#158]
Hello
How can I solve the halo problem? I tried many mode combinations, After demosaicing is done, but there is a layer of Thin halo enveloped, This is especially evident in basicVSR-pp-8x-std-ep1 and basicVSR-pp-8x-std-ep2. thanks.

**Comment by km2ii** [comment]
It is difficult to solve this problem, because the image cannot be restored 100%.
