### ISSUE TITLE
TLA denoise of large dimension input images causing machine to crash and hang

### ISSUE THREAD

**Issue by cetaph230** [km2ii/JVP_TG-PLUS#159]
![2023-05-08_10-28-34](https://user-images.githubusercontent.com/130883321/236891048-4283f095-fe38-4d40-94f1-ceb4c30c877d.jpg)

I noticed when denoising with TLA model, on large dimension files (usually generated from Km2ii 8X super resolution models), the machine will hang very quickly -- usually in the first five or ten input folders. 

CPU is i5-11400 at 2.6 Ghz.
16GB RAM.
GPU is RTX 3070

**Comment by cetaph230** [comment]
Also, i noticed 8x super resolution ignores the dimension size limiter (for example, in the above screenshot, the initial super resolution is generating dimension 608,1936, even though size limit of 1920 is specified in the configuration file.

**Comment by goatsyf** [comment]
16gb is too less for denoise

**Comment by Hellgate4** [comment]
TIA eats the most memory when removing noise
It is recommended to use at least 32 gigabytes.
And the input pixel size is too big.

**Comment by cetaph230** [comment]
I will increase RAM in the system and report results here.

**Comment by hzg4027** [comment]
I suspect there is a memory leak issue, even my 64GB memory will be fully occupied.

**Comment by cetaph230** [comment]
I upgraded my 16GB RAM to 64GB. After running a test file, I believe the issue has been resolved and the machine no longer freezes while denoising with TLA.
