### ISSUE TITLE
The ConfigTools.exe error (v0.3.03.20 with "patcher(20230506)")

### ISSUE THREAD

**Issue by tomeleon** [km2ii/JVP_TG-PLUS#161]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "ConfigTools.py", line 22, in init ConfigTools
ModuleNotFoundError: No module named 'webbrowser'

**Comment by teijiIshida** [comment]
Same issue as https://github.com/km2ii/JVP_TG-PLUS/issues/157

Use the ConfigTools (5.41MB) from the "TG-Plus for JVP_1.12b v0.3.03.20 (2.63 GB)."
