### ISSUE TITLE
Using TG-Plus patcher(20230506), if I use the ▽ function, although all the processes can run smoothly, the resulting MP4 cannot be played normally.

### ISSUE THREAD

**Issue by Great168** [km2ii/JVP_TG-PLUS#162]
I encount a problem. Every time, in the latest version of the program, TG-Plus v.03.03.20a with patcher(20230506), if I use the ▽ function to skip the non-mask part, although all the processes can run smoothly, the resulting MP4 cannot be played normally. Wonder if anyone else has the same problem?

**Comment by km2ii** [comment]
The video synthesis is handled by the main jvp program, not a function of this mod.
It is recommended to select safe mode for record, which is currently the most stable mode.
