### ISSUE TITLE
esrgan-se-2x about 10 times slower than other models

### ISSUE THREAD

**Issue by suphamster** [km2ii/JVP_TG-PLUS#165]
Is it possible to make it faster coz for such slow speed it don't worth efforts? It seems than unlike other models it processes images one by one and not several images at one time.
 
![esrgan](https://github.com/km2ii/JVP_TG-PLUS/assets/17669188/d947a35d-8099-4c52-8405-b6f0ac95e5d0)

**Comment by km2ii** [comment]
Yes, it is very slow.
For test purposes only.
