### ISSUE TITLE
tecogan-da error

### ISSUE THREAD

**Issue by goatsyf** [km2ii/JVP_TG-PLUS#166]
i changed my gpu,when i use tecogan or bvpp,it works normally.when i use tecogan-da,it doesn't work.
![Desktop 2023 06 01 - 22 11 55 01 mp4_20230602_155557 656](https://github.com/km2ii/JVP_TG-PLUS/assets/120884567/0a517219-1b5a-4574-89c5-7bbc140cc959)
![Desktop 2023 06 01 - 22 11 55 01 mp4_20230602_155646 742](https://github.com/km2ii/JVP_TG-PLUS/assets/120884567/43e894af-97a5-4eaf-8883-c7804fdc3124)

![2023-06-01](https://github.com/km2ii/JVP_TG-PLUS/assets/120884567/4adf2eaa-4132-4f1d-862a-7a2214995b1e)

**Comment by suphamster** [comment]
Use search next time: https://github.com/km2ii/JVP_TG-PLUS/issues/100#issuecomment-1409707597

**Comment by goatsyf** [comment]
> Use search next time: [#100 (comment)](https://github.com/km2ii/JVP_TG-PLUS/issues/100#issuecomment-1409707597)

I tried as you said，It doesn't work.Which version of duda and cudnn do you use？

**Comment by suphamster** [comment]
Read **my** comment where is direct link to **all** needed dll https://github.com/km2ii/JVP_TG-PLUS/issues/100#issuecomment-1572011927
P.S. I may be wrong by TG+ actuallly don't need **installed** Cuda + cudnn if u already placed all needed dll files from it in both mentioned by me folder (..\torch\lib and ..\TGMain).
