### ISSUE TITLE
Can I adjust the Vram setting so that it include the Shared Vram (Shared GPU Memory)

### ISSUE THREAD

**Issue by georgechoo1990** [km2ii/JVP_TG-PLUS#167]
Hi there, I always encounter issue that cause by not sufficient Vram (input not match output), so i wonder if I can adjust the Vram setting higher so that it include the Shared Vram (Shared GPU Memory)

example
RTX2060 6gb dedicated Vram
then I have another 8gb Shared GPU memory

So i increase the Vram setting in Javplayer to over 6gb

Will this solve the problem and make it run better? or it will impact performance and best to avoid?

thanks

**Comment by km2ii** [comment]
It seems that shared memory cannot be used like this.
