### ISSUE TITLE
stuck at tg-da forever but no error message

### ISSUE THREAD

**Issue by kanchingkuen02** [km2ii/JVP_TG-PLUS#170]
running 1.12b with the latest patch.
tried stop and resume and still  get stuck at the same png
below is copy paste from the terminal

###

[info] mPlus list:
       * m1 - tecogan-da:tecoGAN-da-8x-std:8X
       * m2 - downscale::4x
       * m3 - basicVSR-pp:basicVSR-pp-4x-std:4X
       * m4 - denoise:tla:medium
       * m5 - tecogan:UE-4X:4X
[info] * mPlus m1 - TECOGAN-DA:tecoGAN-da-8x-std:8X.
tecogan-da.exe --input_dir E:\JavPlayer_112b\JavPlayer_112b\TG\input12 --output_dir E:\JavPlayer_112b\JavPlayer_112b\TG\output12 --checkpoint E:\JavPlayer_112b\JavPlayer_112b\TG\TG-MODEL\tecoGAN-da-8x-std --imgext png --n_count 60 --warm_inter 5 --offset_x 0 --offset_y 0
[info] E:\JavPlayer_112b\JavPlayer_112b\TG\TG-MODEL\tecoGAN-da-8x-std.pth loaded.
 input shape: [62, 106]
 output shape: [496, 848]

TG-Plus v0.3.03.20a  Tasks: [13/97]                                     Stages: [Tecogan-da]                                     Time:[00:04|04:38:25]* mPlus1 tecogan-da:tecoGAN-da-8x-std:8                                                                   00:16  100.00%                    E:\JavPlayer_112b\JavPlayer_112b\TG\output12 1005.png

####
any idea? thanks in advance.

**Comment by suphamster** [comment]
I have some performance issue with tg-da also. Some stages goes very fast but other very slow (about 3 stages fast and then 3 slow and so on). Also I have suggestion that it's related to settings in JavPlayer: if output images format set to png/png then tg-da processing slower, but if png/jpg then faster but I'm not 100% sure and this needs to be tested more.

**Comment by suphamster** [comment]
> > any idea? thanks in advance.
> > (about 3-5 stages fast and then 1-3 slow and so on)
> 
> Neither of these two problems has been encountered. The reason for the fast and slow may be due to the different sizes of the input images.
I think my issue could be related to the latest NVIDIA drivers, more info here https://forums.guru3d.com/threads/nvidia-geforce-game-ready-536-23-whql-download-discussion.448317/#post-6141392 anyway settings n_count value lower seems fixes speed problem.

**Comment by TC-201** [comment]
How can I change the value of n_count?

**Comment by suphamster** [comment]
> How can I change the value of n_count?

In ..\TG\config.ini file directly in [others] section or using "ConfigTools.exe" also others tab at the botton in TG -DA params.
