### ISSUE TITLE
Use anime model (BVPP-STA1, BVPP-STA2,etc...) with TG-PLUS

### ISSUE THREAD

**Issue by tqdungctuct** [km2ii/JVP_TG-PLUS#171]
Hi, I want to use the model for anime like BVPP-STA1, BVPP-STA2 with TG-PLUS. I tried to copy from the basic-vsr model folder to the tg-model folder, and then I renamed it, but it is not working. Can you help me with that? Thank you very much.

**Comment by km2ii** [comment]
No support for anime models, no time to train for anime model.

**Comment by tqdungctuct** [comment]
understood :(
