### ISSUE TITLE
Error "Please update TG-PLUS"

### ISSUE THREAD

**Issue by teijiIshida** [km2ii/JVP_TG-PLUS#173]
Hello, 

I'm using JavPlayer 2.0a with TG-Plus v0.3.03.20a. It has been working good for months, but today, all of a sudden, I'm getting this error. Does anyone know how to fix it?
![2023-06-30 19_32_16-ConfigTools v0 3 03 20a](https://github.com/km2ii/JVP_TG-PLUS/assets/33733459/1bb137b4-eef3-4ec1-9b72-82b5d4d46157)

Edit:
I even tried the old JavPlayer v1.12b with TG-Plus v03.03.20a, but it still shows the error (doesn't matter what model).

**Comment by Chenqqingyang** [comment]
Same request, it should be related to date expiration

**Comment by taro6222** [comment]
I too am having the same problem. how can i solve it?

"Same request, it should be related to date expiration"
I can't understand the meaning.

**Comment by vu84b4** [comment]
我也是同樣的問題，請問該如何解決?

**Comment by SyntaxError1871** [comment]
I am having the same issue too.

**Comment by gdf3678110** [comment]
mplus里面只能存在一条效果，超过一条就会报错

**Comment by tw042449** [comment]
same issue too

**Comment by sweetpotato633** [comment]
same issue. only one model can be selected once upon a time, or the tgplus will report error.

**Comment by km2ii** [comment]
Thank you for your support. The next version update will be released over the weekend.

**Comment by chatchatlotus** [comment]
nice job km2ii, is there any way to make a donation, I really appreciate your wonderful job.

**Comment by unicaja** [comment]
> nice job km2ii, is there any way to make a donation, I really appreciate your wonderful job.

You can buy him a coffee on ko-fi.com.

**Comment by km2ii** [comment]
Apologies, the update has been delayed due to a bug found during testing.

**Comment by Hellgate4** [comment]
> Apologies, the update has been delayed due to a bug found during testing.

Then when will you be able to update it?
