### ISSUE TITLE
Random stuck during super resolution at 100%

### ISSUE THREAD

**Issue by georgechoo1990** [km2ii/JVP_TG-PLUS#174]
![Screenshot 2023-07-05 091958](https://github.com/km2ii/JVP_TG-PLUS/assets/135129667/3b2e3eff-5db5-45f9-8971-534afaadf312)

I encountered an issue during the super-resolution stage where it would randomly get stuck at 100% and refuse to proceed to the next processing part, but there is no error code, any ideas how to solve this？

**Comment by georgechoo1990** [comment]
![Screenshot 2023-07-05 105504](https://github.com/km2ii/JVP_TG-PLUS/assets/135129667/a18893ab-19cb-41e8-8c04-46eee8ea8d29)

saving image more than 100%, what cause this kind of error?

**Comment by km2ii** [comment]
Wait for the update, the next version will be released soon.
