### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by sendxmedic** [km2ii/JVP_TG-PLUS#175]
Not sure why and didnt have a problem opening the last version of TG-Plus but after copying over the files and replacing the older version of ConfigTools i get the Unhandled exception in script (picture shown below). Any help would be great.

![image](https://github.com/km2ii/JVP_TG-PLUS/assets/20912633/e5ffccb9-9ffa-4604-bc22-3df40138a13f)

**Comment by janlucp13** [comment]
Same issue. Try to change the system path ref to python 3.6 and still have the same issue. please help.

**Comment by janlucp13** [comment]
Re unzip the origin version javplayer zip file then apply the patch will solve the issue.

**Comment by Great168** [comment]
> Re unzip the origin version javplayer zip file then apply the patch will solve the issue.

I encountered similar problem, I follow re-unzip the origin version of javplayer zip file and apply the patch, but it is not workable.

**Comment by wwallace55** [comment]
I tested a fresh install like this and still get the error:

- Install JavPlayer 2.00a with ffmpeg in JavPlayer directory
- Install TecoGAN_111
- Install BasicVSR++_111a
- Install Real-ESRGAN_111
- Install TG-Plus for JVP_1.12b+2.0 v0.3.07.12
- Install v.03.07.12_patcher(20230713)
- I get this error when starting ConfigTools.exe

![Error1](https://github.com/km2ii/JVP_TG-PLUS/assets/139407253/95e10914-dd7c-4326-9f8e-e3c9cef04357)
