### ISSUE TITLE
Delete Preset Save Feature

### ISSUE THREAD

**Issue by Hellgate4** [km2ii/JVP_TG-PLUS#176]
The part that was made possible with the previous five presets was lost in this version.
I wonder if it was intentionally updated.

Also, I wonder exactly what "limit the processing data directories to 30." means.

If there are 30 processes that can be recognized continuously, can I judge it by 30 = time?
Usually, 10 minutes of continuous mosaic recognition is more than 30 processes, and an average of 50 to 60 processes are generated.
I wonder if you have set a limit in consideration of the long-term mosaic sanctions.

Even so, it is judged that the number of process generation is too small.

**Comment by km2ii** [comment]
1.[ConfigTools_preset_patch_0712](https://workupload.com/file/dWWFCEMEHec) Repair presets.
2.No, just the first 30 directories are processed, beyond that the source files are copied directly. For less complex scenarios, the aim is to limit the processing time to about 5 minutes, limiting commercial use.

**Comment by Hellgate4** [comment]
> 1.[ConfigTools_preset_patch_0712](https://workupload.com/file/dWWFCEMEHec) Repair presets. 2.No, just the first 30 directories are processed, beyond that the source files are copied directly. For less complex scenarios, the aim is to limit the processing time to about 5 minutes, limiting commercial use.

Oh, thank you for your kind and detailed reply.

**Comment by Hellgate4** [comment]
> 1.[ConfigTools_preset_patch_0712](https://workupload.com/file/dWWFCEMEHec) Repair presets. 2.No, just the first 30 directories are processed, beyond that the source files are copied directly. For less complex scenarios, the aim is to limit the processing time to about 5 minutes, limiting commercial use.

Thank you for your kind reply.

**Comment by Hellgate4** [comment]
I think 5 minutes is too short
I'd like to ask you if you have any plans to increase the time at all.
