### ISSUE TITLE
unhandled exception in script error

### ISSUE THREAD

**Issue by dz1gasd** [km2ii/JVP_TG-PLUS#178]
When I open the 'ConfigTools.exe' file, I get this error message
-------------------------------------------------------------------------------------------

Failed to execute script 'pyi_rth_win32comgenpy' due to unhandled exception: Module use of python36.dll conflicts with this version of Python.

Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 58, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 42, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "win32com\__init__.py", line 9, in <module>
ImportError: Module use of python36.dll conflicts with this version of Python.

**Comment by DDDn612** [comment]
You are not along. I have the same error too!

**Comment by wwallace55** [comment]
I tested a fresh install of JavPlayer 2.00a like this:

- Install JavPlayer 2.00a with ffmpeg in JavPlayer directory
- Install TecoGAN_111
- Install BasicVSR++_111a
- Install Real-ESRGAN_111
- Install TG-Plus for JVP_1.12b+2.0 v0.3.07.12
- Install v.03.07.12_patcher(20230713)
- I get this error when starting ConfigTools.exe

![Error1](https://github.com/km2ii/JVP_TG-PLUS/assets/139407253/5d538b86-ca97-49f9-8f97-b8d9b476c2e5)

**Comment by DDDn612** [comment]
Hi, I followed the suggested by "Kattaklyzm" and have a clean install of javplayer but not TecoGAN_111. Then install TG plus and the error has gone. Please give it a try.

**Comment by km2ii** [comment]
**Note that the v.03.07.12 python environment is 3.10.11, which is different from older version and cannot be installed by overwrite.**

Install JavPlayer 2.00a with ffmpeg in JavPlayer directory
~~Install TecoGAN_111
Install BasicVSR++_111a
Install Real-ESRGAN_111~~
Install TG-Plus for JVP_1.12b+2.0 v0.3.07.12
Install v.03.07.12_patcher(20230713)
