### ISSUE TITLE
Error when applying preservice patch

### ISSUE THREAD

**Issue by Hellgate4** [km2ii/JVP_TG-PLUS#180]
As shown in the title, after patching, the processing itself fails and an error occurs as it moves on.
Please check.

https://github.com/km2ii/JVP_TG-PLUS/assets/100894620/4030c406-6c19-4002-a62f-aa607ee3ec98

**Comment by Hellgate4** [comment]
> As shown in the title, after patching, the processing itself fails and an error occurs as it moves on. Please check.
> Restoring to pre-patch works fine.
>  2023-07-12_20-15-26-415.mp4

**Comment by newborn2010** [comment]
![2023-07-12_200200](https://github.com/km2ii/JVP_TG-PLUS/assets/5358179/a024d94f-d144-469c-861d-4bb976c46665)
I have a clean v0.3.07.12 in TG folder but it fails at the super-sample procedure. Last v0.3.03.20 works fine with same settings.

**Comment by newborn2010** [comment]
New v.03.07.12_patcher(20230713) solves my problem.
