### ISSUE TITLE
"v.03.07.12_patcher(20230713)" still can't solve the problem

### ISSUE THREAD

**Issue by mark8957** [km2ii/JVP_TG-PLUS#182]
![image](https://github.com/km2ii/JVP_TG-PLUS/assets/126434731/af82f669-289b-46eb-afea-f3d919f1773f)

**Comment by Kattaklyzm** [comment]
I had this problem,  I solved it by doing a clean install of JavPlayer,  then installing TG-Plus into that folder.  I may be wrong, but it seems to me that TecoGAN_111 doesn't play nice with ConfigTools,exe

**Comment by DDDn612** [comment]
Thank you Kattaklyzm. Your suggestion really solve the problem. Just install javplayer but not TecoGAN_111. Then install TG plus and it works fine. Anyone has this problem, please give it a trial.

**Comment by dz1gasd** [comment]
Thanks Kattaklyzm. you're right. TecoGan_111 has problem. Don't install TecoGAN_111. Just install TG plus. BASICvsr++ and real esrgan are install OK.
I installed JAVplayer 2.0a - TG plus- 7/13 patch - BASICvsr++ - realesrgan

**Comment by km2ii** [comment]
![image](https://github.com/km2ii/JVP_TG-PLUS/assets/55206195/173ada9b-db1e-4377-9b5a-08fbe84b400e)

**Comment by dz1gasd** [comment]
Install python 3.10.11 
I solved problem :)
