### ISSUE TITLE
Inquiries about updates

### ISSUE THREAD

**Issue by pyoseong** [km2ii/JVP_TG-PLUS#185]
For newer versions, when proceeding with the BVPP filter

Crack clarity decreases after more than 5 minutes.

Is this due to an update?

Is it impossible to use it like the previous version?

**Comment by Hellgate4** [comment]
30 processes in a process
5 minutes in time..
It was updated the other day and adjusted to 50 processes.

You know why, but the long process for commercial sanctions is sanctioned. It's the producer's intention.

It is true that time is too short.
If I can get 100 through the process..

**Comment by pyoseong** [comment]
Are you saying that you can make 50 5-minute videos into one video? 
Is it now impossible to encode the entire image?

> 30 processes in a process 5 minutes in time.. It was updated the other day and adjusted to 50 processes.
> 
> You know why, but the long process for commercial sanctions is sanctioned. It's the producer's intention.
> 
> It is true that time is too short. If I can get 100 through the process..



If it's a 120 minute video

After editing about 24 cuts

Are you saying that we need to work on the merger later?

**Comment by Hellgate4** [comment]
The previous version is not available. There is no way to use it.
Only the new version is available, and it is created with a new Python environment, so if you overwrite the previous version, it will not work.

Only the version currently produced by the producer can be used.

> > 30 processes in a process 5 minutes in time.. It was updated the other day and adjusted to 50 processes.
> > You know why, but the long process for commercial sanctions is sanctioned. It's the producer's intention.
> > It is true that time is too short. If I can get 100 through the process..
> 
> If it's a 120 minute video
> 
> After editing about 24 cuts
> 
> Are you saying that we need to work on the merger later?
> 
> And if you haven't updated it to the latest version yet
> 
> Is the previous version still available?

The previous version is not available. There is no way to use it.
Only the new version is available, and it is created with a new Python environment, so if you overwrite the previous version, it will not work.

Only the version currently produced by the producer can be used.

**Comment by pyoseong** [comment]
> > > 30 processes in a process 5 minutes in time.. It was updated the other day and adjusted to 50 processes.
> > > You know why, but the long process for commercial sanctions is sanctioned. It's the producer's intention.
> > > It is true that time is too short. If I can get 100 through the process..
> > 
> > 
> > If it's a 120 minute video
> > After editing about 24 cuts
> > Are you saying that we need to work on the merger later?
> > And if you haven't updated it to the latest version yet
> > Is the previous version still available?
> 
> The previous version is not available. There is no way to use it. Only the new version is available, and it is created with a new Python environment, so if you overwrite the previous version, it will not work.
> 
> Only the version currently produced by the producer can be used.

Oh my gosh...
I'll have to wait for the producer to release a paid version without restrictions on processing.
I'm going to buy it.
