### ISSUE TITLE
veai.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by sancho63** [km2ii/JVP_TG-PLUS#37]
I receive this error when JP runs TG-PLUS or I launch the configuration tool...
![error_crop](https://user-images.githubusercontent.com/92683186/137634529-94d22845-3f24-4a3d-bb0f-879fd61ca96a.png)

jp109a and veai have both been running fine previously

**Comment by grv888** [comment]
which version of topaz is it?

**Comment by km2ii** [comment]
You can customize the execution, not must use veai.
