### ISSUE TITLE
JP v1.11a safe mode not working  (black screen)

### ISSUE THREAD

**Issue by suphamster** [km2ii/JVP_TG-PLUS#63]
Slow mode works but crashes at final encoding stage (with h265 codec, h264 works).

**Comment by FrankLinxzx** [comment]
> Slow mode works but crashes at final encoding stage (with h265 codec, h264 works).

it say not support 265 in thedocument file

**Comment by suphamster** [comment]
> > Slow mode works but crashes at final encoding stage (with h265 codec, h264 works).
> 
> it say not support 265 in thedocument file
It worked in JP v1.11 before for me. At least in safe mode...

**Comment by km2ii** [comment]
> Slow mode works but crashes at final encoding stage (with h265 codec, h264 works).

![image](https://user-images.githubusercontent.com/55206195/158213211-3cba3ce5-f629-4717-96d5-fbefba22205a.png)
Test it, indeed h265 encoding crash, but this should be feedback to the author.

**Comment by suphamster** [comment]
> > Slow mode works but crashes at final encoding stage (with h265 codec, h264 works).
> 
> ![image](https://user-images.githubusercontent.com/55206195/158213211-3cba3ce5-f629-4717-96d5-fbefba22205a.png) Test it, indeed h265 encoding crash, but this should be feedback to the author.
And what about safe mode? It works for u then u can close this issue since this version is bad for me anyway because of yellow effect...

**Comment by grv888** [comment]
![image](https://user-images.githubusercontent.com/63555514/159022759-81122c27-edcd-444c-a379-2e0f46868378.png)
 about safe mode

**Comment by IIJlOXOCIIAJl** [comment]
It's so funny I don't get any error. When I press start I just see a black screen in safe mode.

**Comment by IIJlOXOCIIAJl** [comment]
> > It's so funny I don't get any error. When I press start I just see a black screen in safe mode.
> 
> Just download latest version and everything will be fixed(1.11b), atleast for me.

Thanks for the answer. And for the advice too. I'll try today.

**Comment by IIJlOXOCIIAJl** [comment]
> > It's so funny I don't get any error. When I press start I just see a black screen in safe mode.
> 
> Just download latest version and everything will be fixed(1.11b), atleast for me.
I managed to find only version "JavPlayerTrial_111b" Do you use the same one?

**Comment by suphamster** [comment]
JP v1.12b absolutely same error with [TG-Plus for JVP_1.12b v0.3.02.02](https://workupload.com/archive/jxU4HGyx) I mean black screen in safe mode and crash at final encoding... Tested almost all encoders (not matter h264 or h265) but everyone seems crashes at final stage.
`Active code page: 65001

G:\JavPlayer_112b>ffmpeg -ss 144.0562 -i "G:/JavPlayer_112b/sample/venu-475 Maika Asai.mp4" -ss 0 -start_number 0 -t 32.86551 -r 89.65 "G:/JavPlayer_112b/TG/rawBuffer/"G:\JavPlayer_112b\ExtractionTest.bat"6d.png"
ffmpeg version git-2022-10-11-4797476-ffmpeg-windows-build-helpers Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10.2.0 (GCC)
  configuration: --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/runner/work/ffmpeg-autobuild/ffmpeg-autobuild/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1 --enable-libvpx --enable-libaom --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lshlwapi --extra-libs=-lmpg123 --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags='-mtune=generic' --extra-cflags=-O3 --enable-static --disable-shared --prefix=/home/runner/work/ffmpeg-autobuild/ffmpeg-autobuild/ffmpeg-source --enable-nonfree --enable-libfdk-aac --enable-decklink
  libavutil      57. 39.101 / 57. 39.101
  libavcodec     59. 50.100 / 59. 50.100
  libavformat    59. 34.101 / 59. 34.101
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 49.101 /  8. 49.101
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'G:/JavPlayer_112b/sample/venu-475 Maika Asai.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.27.100
  Duration: 00:00:05.69, start: 726.611000, bitrate: 17188 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 17184 kb/s, 89.65 fps, 90 tbr, 90k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'G:/JavPlayer_112b/TG/rawBuffer/G:\JavPlayer_112b\ExtractionTest.bat6d.png':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.34.101
  Stream #0:0(und): Video: png, rgb24, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 89.65 fps, 89.65 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.50.100 png
frame=    0 fps=0.0 q=0.0 Lsize=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A    /s speed=N/A
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)`
I think problems in wrong generated path `G:/JavPlayer_112b/TG/rawBuffer/G:\JavPlayer_112b\ExtractionTest.bat6d.png` but I dunno how to fix it...
