### ISSUE TITLE
my TG-Plus always using the CPU, need help plz 😢😢

### ISSUE THREAD

**Issue by PSCrazyCatxx** [km2ii/JVP_TG-PLUS#97]
windows 10 22H2
cpu: 5900x
gpu: 3080
ram: 32GB
cudnn_v8.1.1.33_cuda_11.2
cuda_11.1.1_456.81

JP1.12b
TG-Plus for JP_109a-1.12a v0.2.10.20
ConfigTools :BVPPst_80000-td-UE_4X
its always use CPU run job, CPU70% GPU10% like this lol
I dont know whats wrong 🤣 need help plz

**Comment by firebfm** [comment]
Have you followed all steps from this guide? https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-windows
Every step is important like 2.1.3. Installing Zlib, 2.2. Downloading cuDNN for Windows, copying bin, include, lib folder and editing environment variables.
I have CUDA Toolkit 12.0 and cudnn v8.7.0.84 installed and no problems.

**Comment by calro-lam** [comment]
me too, it always using the cpu.  my gpu is amd rx6600m and cpu is r7 5800h. i don't know how to solve thx problem
